import Chat from "@/components/Chat/Chat";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import MessagesProvider from "@/context/messages";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //? Set `suppressHydrationWarning={true}`, as an unwanted extension in the browser is passing unwanted attributes
  return (
    <html lang="en">
      <MessagesProvider>
        <Providers>
          <body className={inter.className} suppressHydrationWarning={true}>
            <Chat />
            {children}
          </body>
        </Providers>
      </MessagesProvider>
    </html>
  );
}
